/*
 * Scala.js (https://www.scala-js.org/)
 *
 * Copyright EPFL.
 *
 * Licensed under Apache License 2.0
 * (https://www.apache.org/licenses/LICENSE-2.0).
 *
 * See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 */

package org.scalajs.testing.bridge

import scala.scalajs.js
import scala.scalajs.js.annotation._
import scala.scalajs.LinkingInfo
import scala.scalajs.LinkingInfo.linkTimeIf

/* Use the queue execution context (based on JS promises) explicitly:
 * We do not have anything better at our disposal and it is accceptable in
 * terms of fairness: JSRPC only handles in-between test communcation, so any
 * future chain will "yield" to I/O (waiting for a message) or an RPC handler in
 * a finite number of steps.
 */
import scala.scalajs.concurrent.JSExecutionContext.Implicits.queue

import scala.concurrent.duration._

import org.scalajs.testing.common.RPCCore

/** JS RPC Core. Uses `scalajsCom`. */
private[bridge] final object JSRPC extends RPCCore {
  linkTimeIf(LinkingInfo.targetPureWasm) {
    ScalajsCom.init()
  } {
    Com.init(handleMessage _)
  }

  /** The method referenced by the ScalajsCom.init function,
   *  whose real body is generated by the `wasmemitter.ClassEmitter#emitSpecialMethod`.
   *  This method is not intended to be used directly from a Scala program.
   */
  @noinline
  def handleMessage0(msg: String): Unit =
    handleMessage(msg)

  override protected def send(msg: String): Unit = {
    linkTimeIf(LinkingInfo.targetPureWasm) {
      ScalajsCom.send(msg)
    } {
      Com.send(msg)
    }
  }

  @js.native
  @JSGlobal("scalajsCom")
  private object Com extends js.Object {
    def init(onReceive: js.Function1[String, Unit]): Unit = js.native
    def send(msg: String): Unit = js.native
    // We support close, but do not use it. The JS side just terminates.
    // def close(): Unit = js.native
  }
}

private[bridge] final object ScalajsCom {
  @noinline
  def send(msg: String): Unit = {}

  @noinline
  def init(): Unit = {
    // This is a dummy call to make handleMessage0 reachable.
    // We cannot use SymbolRequirement because handleMessage0 is only
    // available in the Test scope, but the linker has no idea it's in Test.
    JSRPC.handleMessage0("")
  }
}
