/*
 * Scala.js (https://www.scala-js.org/)
 *
 * Copyright EPFL.
 *
 * Licensed under Apache License 2.0
 * (https://www.apache.org/licenses/LICENSE-2.0).
 *
 * See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 */

/* Port test data from FreeBSD for log, log10, and log1p:
 * - https://github.com/freebsd/freebsd-src/blob/9b0102837e305ca75de2bc14d284f786a33f9a6a/lib/msun/tests/logarithm_test.c
 *
 * Copyright (c) 2008-2010 David Schultz <das@FreeBSD.org>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

package org.scalajs.testsuite.javalib.lang

import org.junit.Test
import org.junit.Assert._

import java.lang.{Double => JDouble}
import java.lang.{Math, StrictMath}

import org.scalajs.testsuite.utils.AssertExtensions.assertExactEquals
import org.scalajs.testsuite.javalib.lang.data._
class StrictMathTest {

  @Test def log(): Unit = {
    assertExactEquals(Double.NegativeInfinity, StrictMath.log(-0.0))
    assertExactEquals(Double.NegativeInfinity, StrictMath.log(0.0))
    assertTrue(StrictMath.log(Double.NaN).isNaN)
    assertExactEquals(Double.PositiveInfinity, StrictMath.log(Double.PositiveInfinity))
    assertTrue(StrictMath.log(Double.NegativeInfinity).isNaN)
    assertExactEquals(0.0, StrictMath.log(1.0))
    assertTrue(StrictMath.log(-1.0).isNaN)

    /* Generated by
     *
     * ```
     * @main def main(): Unit =
     *   import java.lang.StrictMath
     *   Array(
     *     (StrictMath.scalb(1.0, -120) + StrictMath.scalb(1.0, -140), "0x1p-120 + 0x1p-140"),
     *     (1.0 - StrictMath.scalb(1.0, -20), "1.0 - 0x1p-20"),
     *     (1.0 + StrictMath.scalb(1.0, -20), "1.0 + 0x1p-20"),
     *     (19.75, "19.75"),
     *     (19.75 * StrictMath.scalb(1.0, 100), "19.75 * 0x1p100")
     *   ).foreach { (input, c) =>
     *     val result = StrictMath.log(input)
     *     println(s"assertExactEquals(\"log($c)\", $result, StrictMath.log($input))")
     *   }
     * ```
     */
    assertExactEquals("log(0x1p-120 + 0x1p-140)", -83.17766071351957, StrictMath.log(7.523171019910777E-37))
    assertExactEquals("log(1.0 - 0x1p-20)", -9.5367477115389E-7, StrictMath.log(0.9999990463256836))
    assertExactEquals("log(1.0 + 0x1p-20)", 9.536738616591883E-7, StrictMath.log(1.0000009536743164))
    assertExactEquals("log(19.75)", 2.9831534913471307, StrictMath.log(19.75))
    assertExactEquals("log(19.75 * 0x1p100)", 72.29787154734166, StrictMath.log(2.503609935450753E31))
  }

  @Test def log10(): Unit = {
    assertExactEquals(Double.NegativeInfinity, StrictMath.log10(-0.0))
    assertExactEquals(Double.NegativeInfinity, StrictMath.log10(0.0))
    assertTrue(StrictMath.log10(Double.NaN).isNaN)
    assertExactEquals(Double.PositiveInfinity, StrictMath.log10(Double.PositiveInfinity))
    assertTrue(StrictMath.log10(Double.NegativeInfinity).isNaN)
    assertExactEquals(0.0, StrictMath.log10(1.0))
    assertTrue(StrictMath.log10(-1.0).isNaN)

    assertExactEquals("log10(0x1p-120 + 0x1p-140)", -36.12359906550245, StrictMath.log10(7.523171019910777E-37))
    assertExactEquals("log10(1.0 - 0x1p-20)", -4.1417569064248085E-7, StrictMath.log10(0.9999990463256836))
    assertExactEquals("log10(1.0 + 0x1p-20)", 4.141752956539506E-7, StrictMath.log10(1.0000009536743164))
    assertExactEquals("log10(19.75)", 1.295567099962479, StrictMath.log10(19.75))
    assertExactEquals("log10(19.75 * 0x1p100)", 31.398566666360598, StrictMath.log10(2.503609935450753E31))
  }

  @Test def log1p(): Unit = {
    assertExactEquals(-0.0, StrictMath.log1p(-0.0))
    assertExactEquals(0.0, StrictMath.log1p(0.0))
    assertTrue(StrictMath.log1p(Double.NaN).isNaN)
    assertExactEquals(Double.PositiveInfinity, StrictMath.log1p(Double.PositiveInfinity))
    assertTrue(StrictMath.log1p(Double.NegativeInfinity).isNaN)
    assertExactEquals(Double.NegativeInfinity, StrictMath.log1p(-1.0))
    assertTrue(StrictMath.log1p(-1.5).isNaN)

    assertExactEquals("log1p(-0x1p-20)", -9.5367477115389E-7, StrictMath.log1p(-9.5367431640625E-7))
    assertExactEquals("log1p(0x1p-20)", 9.536738616591883E-7, StrictMath.log1p(9.5367431640625E-7))
    assertExactEquals("log1p(18.75)", 2.9831534913471307, StrictMath.log1p(18.75))
    assertExactEquals("log1p(18.75 * 0x1p100)", 72.29787154734166, StrictMath.log1p(2.503609935450753E31))

    assertExactEquals(0.1823215567939546, StrictMath.log1p(0.19999999999999996)) // 0x0.3333333333333p0
    assertExactEquals(-0.2231435513142097, StrictMath.log1p(-0.19999999999999996)) // -0x0.3333333333333p0
  }

  @Test def sqrt(): Unit = {
    // Special cases
    assertExactEquals(-0.0, StrictMath.sqrt(-0.0))
    assertExactEquals(0.0, StrictMath.sqrt(0.0))
    assertTrue(StrictMath.sqrt(Double.NaN).isNaN)
    assertExactEquals(Double.PositiveInfinity, StrictMath.sqrt(Double.PositiveInfinity))
    assertTrue(StrictMath.sqrt(Double.NegativeInfinity).isNaN)
    assertTrue(StrictMath.sqrt(-1.0).isNaN) // sqrt(-ve) = NaN

    StrictMathSqrt.data.foreach { case (expectedHex, inputHex) =>
      val expected = JDouble.parseDouble(expectedHex)
      val input = JDouble.parseDouble(inputHex)
      val actual = StrictMath.sqrt(input)
      // Bionic uses 1 ULP tolerance, but it passes with 0 ULP
      // https://android.googlesource.com/platform/bionic/+/refs/heads/main/tests/math_test.cpp#2219
      assertExactEquals(s"sqrt($inputHex)", expected, actual)
    }
  }

  @Test def pow(): Unit = {
    // Special cases
    // assertTrue(StrictMath.pow(Double.NaN, 3.0).isNaN)
    // assertTrue(StrictMath.pow(1.0, Double.NaN).isNaN)
    // assertTrue(StrictMath.pow(Double.NaN, Double.NaN).isNaN)

    def parseDouble(str: String): Double = {
      if (str == "HUGE_VAL") Double.PositiveInfinity
      else if (str == "-HUGE_VAL") Double.NegativeInfinity
      else JDouble.parseDouble(str)
    }

    StrictMathPow.data.foreach { case (expectedHex, x, y) =>
      val expected = parseDouble(expectedHex)
      val actual = StrictMath.pow(parseDouble(x), parseDouble(y))
      // Bionic uses 1 ULP tolerance
      // https://android.googlesource.com/platform/bionic/+/refs/heads/main/tests/math_test.cpp#2109
      val ulp = Math.ulp(expected)
      assertEquals(s"pow($x, $y)", expected, actual, ulp)
    }
  }
}
